name : primer pasos
  
on :
  push:
    branches:
      - master22
jobs:
  crear-atefacto-alfa1s1:
    runs-on: ubuntu-latest
    steps:

      - name: stpe 1
        run: mkdir alfa
      - name: step 2
        run: |
          cd alfa
          echo 'hola mundo' > algo.html
          cd ..
      - name: step3
        run: zip -r alfa.zip alfa
      - name: step4
        run: ls -la
