name : tarea
on:
  push:
    branches:
      - master1
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        maquina: [ 6, 8, 10]
    steps:
     - name: stpe 1
       run: sudo hostname 
