#2. Realizar un workflow que permita:
#Realizar la ejecución de 3 tareas secuenciales (configuración, construcción y prueba), basada en 3
#scripts de su preferencia
#Publicar los resultados de cada script en un servidor web
#Verificar el acceso a los resultados publicados

name: pregunta 2
on:
  push:
    branches:
      - master
jobs:
  Configuracion:
    runs-on: ubuntu-latest
    services:
      portal-oficina01:
        image: httpd:latest
        ports:
          - 8082:80
        volumes: 
          - /home:/usr/local/apache2/htdocs/

    steps:
      - name: algo de html
        run: echo "hola mundo" > index.html
      - name: Acceder al portal 1
        run: ls -la ~/

      - name: Acceder al portal 2
        run: curl http://localhost:8082
      - name: Informacion nodo
        run: ip add
