#2. Realizar un workflow que permita:
#Realizar la ejecución de 3 tareas secuenciales (configuración, construcción y prueba), basada en 3
#scripts de su preferencia
#Publicar los resultados de cada script en un servidor web
#Verificar el acceso a los resultados publicados

name: pregunta 2
on:
  push:
    branches:
      - master
jobs:
  configuracion:
    runs-on: ubuntu-latest
    steps:
      - name: check out del repositorio
        uses: actions/checkout@v2
        
      - name: ejecucion de la configuracion
        run: sh ./setup_server.sh > /home/runner/configuracion.html 
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: configuracion
          path: /home/runner/configuracion.html
  construccion:
    needs: configuracion
    runs-on: ubuntu-latest
    steps:
      - name: check out del repositorio
        uses: actions/checkout@v2
        
      - name: ejecucion de la configuracion
        run: sh ./buil_server.sh > /home/runner/construccion.html 
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: construccion
          path: /home/runner/construccion.html
  prueba:
    needs: construccion
    runs-on: ubuntu-latest
    steps:
      - name: check out del repositorio
        uses: actions/checkout@v2
        
      - name: ejecucion de la configuracion
        run: sh ./test_server.sh > /home/runner/prueba.html 
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: prueba
          path: /home/runner/prueba.html
  publicar:
    needs: prueba
    runs-on: ubuntu-latest
    services:
      portal-oficina01:
        image: httpd:latest
        ports:
          - 8082:80
        volumes: 
          - /home/runner:/usr/local/apache2/htdocs/

    steps:
      - name: descargar configuracion
        uses: actions/download-artifact@v3
        with:
          name: Artefacto_informe
          path: construccion.zip
      - name: descargar construccion
        uses: actions/download-artifact@v3
        with:
          name: Artefacto_construccion
          path: construccion.zip
      - name: descargar prueba
        uses: actions/download-artifact@v3
        with:
          name: Artefacto_prueba
          path: prueba.zip
      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq construccion.zip -d /home/runner
      
        
      - name: algo de html
        run: |
          cd  /home/runner
          echo "hola mundo" > index.html
      - name: Acceder al portal 1
        run: ls -la /home/runner

      - name: Acceder al portal 2
        run: curl http://localhost:8082
      - name: Informacion nodo
        run: ip add
