name: pregunta 2
on:
  push:
    branches:
      - master2
jobs:
  configuracion:
    runs-on: ubuntu-latest
    steps:
      - name: check out del repositorio
        uses: actions/checkout@v2
        
      - name: ejecucion de la configuracion
        run: sh ./setup_server.sh > /home/runner/configuracion.html 
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: configuracion
          path: /home/runner/configuracion.html
  construccion1:
    needs: configuracion
    runs-on: ubuntu-latest
    steps:
      - name: check out del repositorio
        uses: actions/checkout@v2
        
      - name: ejecucion de la configuracion
        run: sh ./buil_server.sh > /home/runner/construccion1.html 
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: construccion1
          path: /home/runner/construccion1.html
  construccion2:
    needs: configuracion
    runs-on: ubuntu-latest
    steps:
      - name: check out del repositorio
        uses: actions/checkout@v2
        
      - name: ejecucion de la configuracion
        run: sh ./buil_server.sh > /home/runner/construccion2.html 
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: construccion2
          path: /home/runner/construccion2.html
  construccion3:
    needs: configuracion
    runs-on: ubuntu-latest
    steps:
      - name: check out del repositorio
        uses: actions/checkout@v2
        
      - name: ejecucion de la configuracion
        run: sh ./buil_server.sh > /home/runner/construccion3.html 
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: construccion3
          path: /home/runner/construccion3.html
  prueba:
    needs: [construccion1,construccion2,construccion3]
    runs-on: ubuntu-latest
    steps:
      - name: check out del repositorio
        uses: actions/checkout@v2
        
      - name: ejecucion de la configuracion
        run: sh ./test_server.sh > /home/runner/prueba.html 
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: prueba
          path: /home/runner/prueba.html
  publicar:
    needs: prueba
    runs-on: ubuntu-latest
    services:
      portal-oficina01:
        image: httpd:latest
        ports:
          - 8082:80
        volumes: 
          - /home/runner:/usr/local/apache2/htdocs/

    steps:
      - name: descargar configuracion
        uses: actions/download-artifact@v3
        with:
          name: configuracion
          path: /home/runner/configuracion
      - name: descargar construccion1
        uses: actions/download-artifact@v3
        with:
          name: construccion1
          path: /home/runner/construccion1
      - name: descargar construccion2
        uses: actions/download-artifact@v3
        with:
          name: construccion2
          path: /home/runner/construccion2
      - name: descargar construccion3
        uses: actions/download-artifact@v3
        with:
          name: construccion3
          path: /home/runner/construccion3
      - name: descargar prueba
        uses: actions/download-artifact@v3
        with:
          name: prueba
          path: /home/runner/prueba
          
      - name: verificar
        run: |
          mv /home/runner/configuracion/configuracion.html /home/runner/configuracion.html
          mv /home/runner/construccion1/construccion1.html /home/runner/construccion1.html
          mv /home/runner/construccion2/construccion2.html /home/runner/construccion2.html
          mv /home/runner/construccion3/construccion3.html /home/runner/construccion3.html
          mv /home/runner/prueba/prueba.html /home/runner/prueba.html
          echo "<h1>configuracion </h1><iframe src=configuracion.html><h1>construccion1 </h1><iframe src=construccion1.html> <h1>construccion2 </h1><iframe src=construccion2.html> <h1>construccion3 </h1><iframe src=construccion3.html> <h1>prueba </h1><iframe src=prueba.html>"> /home/runner/index.html
       
      - name: Acceder al portal 1
        run: ls -la /home/runner

      - name: Acceder al portal 2
        run: curl http://localhost:8082
      - name: Informacion nodo
        run: ip add
